// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCls--46qt7mJFoSDAFrVajR7po6AZbHrM',
    appId: '1:574398540744:web:c82b6ff8fedd23a7bd6efd',
    messagingSenderId: '574398540744',
    projectId: 'bmi-cali',
    authDomain: 'bmi-cali.firebaseapp.com',
    storageBucket: 'bmi-cali.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBniEnPmTocYXgc2Bx4g21mBC9xddNzoTI',
    appId: '1:574398540744:android:d0eba6f70413a2fabd6efd',
    messagingSenderId: '574398540744',
    projectId: 'bmi-cali',
    storageBucket: 'bmi-cali.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsgQL_w_8rS1lxZK185h458FNVzGN5IFI',
    appId: '1:574398540744:ios:1483aacf4adc3f47bd6efd',
    messagingSenderId: '574398540744',
    projectId: 'bmi-cali',
    storageBucket: 'bmi-cali.appspot.com',
    iosClientId: '574398540744-jgnb0p204skbeugjq6c4776sie7br871.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsgQL_w_8rS1lxZK185h458FNVzGN5IFI',
    appId: '1:574398540744:ios:1483aacf4adc3f47bd6efd',
    messagingSenderId: '574398540744',
    projectId: 'bmi-cali',
    storageBucket: 'bmi-cali.appspot.com',
    iosClientId: '574398540744-jgnb0p204skbeugjq6c4776sie7br871.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmi',
  );
}
